using System;
using System.Collections.Generic;
using System.Linq;

/*
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

*/

namespace FibonacciNumbersEven
{
    class Program
    {

        public static long Fibonacci(long n)
        {
            long a = 0;
            long b = 1;
            // In N steps compute Fibonacci sequence iteratively.
            for (int i = 0; i < n; i++)
            {
                long temp = a;
                a = b;
                b = temp + b;
            }

            return a;
        }

        public static bool CheckEven(long a)
        {
            if (a % 2 == 0)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        static void Main()
        {
            HashSet<long> evenNumbers = new HashSet<long>();

            for (long i = 1; i < 40; i++)
            {

                if (Fibonacci(i) >= 4000000)
                {
                    break;
                }

                if (CheckEven(Fibonacci(i)))
                {

                    evenNumbers.Add(Fibonacci(i));
                }
            }

            Console.WriteLine(evenNumbers.Sum());
        }

    }
}
